version: "3.9"

services: 
  bento:
    image: lewisdoesstuff/bento-next
    volumes:
      # Host path: Container path
      - ./config.ts:/src/config.ts
      - ./.env:/src/.env
    ports:
      # Replace host port 80 (left side) with desired port.
      - 80:8080